export const DESTINATIONS = [
    {
      id:0,
      name: 'Goa',
      description: 'Famous for beaches, nightlife and water sports.',
      image: 'assets/goa.jpg',
      category: 'india',
      rating: 5,
      price: 15000,
      lat: 15.2993,
  lng: 74.1240
    },
    {
      id:1,
      name: 'Manali',
      description: 'A beautiful hill station surrounded by mountains.',
      image: 'assets/jaipur.jpg',
      category: 'international',
      rating: 4,
      price: 65000,
      lat: 32.2396,
  lng: 77.1887
    },
    {
      id:2,
  name: 'Ooty',
  description: 'Queen of hill stations with tea gardens and cool climate.',
  image: 'assets/ooty.jpg',
  category: 'india',
  rating: 5,
    price: 75000,
    lat: 12.2958,
  lng: 76.6394
},
{
  id:3,
  name: 'Mysore',
  description: 'Famous for its royal palace and cultural heritage.',
  image: 'assets/mysore.jpg',
  category: 'india',
  rating: 4,
    price: 18000,
    lat: 12.2958,
    lng: 76.6394
},
{
  id:4,
  name: 'Hyderabad',
  description: 'City of pearls known for Charminar and biryani.',
  image: 'assets/hyd.jpg',
  category: 'india',
  rating: 3,
    price: 5000,
   lat: 17.3850,
  lng: 78.4867
},
{
  id:5,
  name: 'Rishikesh',
  description: 'Yoga capital of the world with river rafting.',
  image: 'assets/ris.jpg',
  category: 'india',
  rating: 2,
    price: 45000,
    lat: 30.0869,
  lng: 78.2676
},
{
  id:6,
  name: 'Shimla',
  description: 'Beautiful hill station with snow and colonial charm.',
  image: 'assets/simla.jpg',
  category: 'india',
  rating: 2,
    price: 45000,
     lat: 31.1048,
  lng: 77.1734
},
{
  id:7,
  name: 'Udaipur',
  description: 'City of lakes with stunning royal palaces.',
  image: 'assets/udai.jpg',
  category: 'india',
  rating: 2,
    price: 54000,
    lat: 24.5854,
  lng: 73.7125
},
{
  id:8,
  name: 'Andaman',
  description: 'Crystal clear waters and peaceful island vibes.',
  image: 'assets/andaman.jpg',
  rating: 5,
    price: 76000,
   lat: 11.6234,
  lng: 92.7265
},
{
  id:9,
  name: 'Coorg',
  description: 'Coffee plantations and misty mountain views.',
  image: 'assets/coorg.jpg',
  rating: 4,
    price: 15000,
    lat: 12.4244,
  lng: 75.7382
},
{
  id:10,
  name: 'Varanasi',
  description: 'Spiritual city with ancient ghats on the Ganga.',
  image: 'assets/kasi.jpg',
  category: 'india',
  rating: 3,
    price: 12000,
    lat: 25.3176,
  lng: 82.9739
},
{
    id:11,
  name: 'Dubai',
  description: 'Adventure paradise with breathtaking landscapes.',
  image: 'assets/dubai.jpg',
  category: 'international',
  rating: 4,
    price: 68000,
    lat: 25.2048,
  lng: 55.2708
},
{
  id:12,
  name: 'Maldives',
  description: 'Luxury island destination with crystal clear waters.',
  image: 'assets/maldives.jpg',
  category: 'international',
  rating: 3,
    price: 27000,
    lat: 1.9777,
  lng: 73.5361
},
{
  id:13,
  name: 'Paris',
  description: 'Luxury destination with crystal lights.',
  image: 'assets/paris.jpg',
  category: 'international',
  rating: 4,
    price: 36000,
lat: 48.8566,
  lng: 2.3522
},
{
  id:14,
  name: 'Switzerland',
  description: 'Luxury destination with spiritual city.',
  image: 'assets/swi.jpg',
  category: 'international',
  rating: 2,
    price: 68000,
   lat: 46.9480,
  lng: 7.4474
},
{
  id:15,
      name: 'Tirupati',
      description: 'Sacred Himalayan temple dedicated to Lord Venkateswara Swamy.',
      image: 'assets/ttd.jpg',
      category: 'india',
      rating: 5,
    price: 1500,
    lat: 13.6288,
  lng: 79.4192
    },
{
  id:16,
  name: 'Kedarnath',
  description: 'Sacred Himalayan temple dedicated to Lord Shiva.',
  image: 'assets/kedarnath.jpg',
  category: 'india',
  rating: 5,
  price: 20000,
  lat: 30.7352,
  lng: 79.0669
},
{
  id:17,
  name: 'Pondicherry',
  description: 'French colonial town with beaches and cafes.',
  image: 'assets/pondi cherry.jpg',
  category: 'india',
  rating: 2,
  price: 12000,
  lat: 11.9416,
  lng: 79.8083
},
{
  id:18,
  name: 'Agra',
  description: 'Home to the iconic Taj Mahal and Mughal heritage.',
  image: 'assets/agra.jpg',
  category: 'india',
  rating: 5,
  price: 15000,
   lat: 27.1767,
  lng: 78.0081
},
{
  id:19,
  name: 'Ayodhya Ram Mandir',
  description: 'Holy birthplace of Lord Rama and spiritual center.',
  image: 'assets/Mandir.jpg',
  category: 'india',
  rating: 5,
  price: 10000,
  lat: 26.7995,
  lng: 82.2043
},
{
  id:20,
  name: 'Arunachalam',
  description: 'Beautiful northeastern state with mountains and monasteries.',
  image: 'assets/arunachalam.jpg',
  category: 'india',
  rating: 2,
  price: 25000,
  lat: 12.2253,
  lng: 79.0747
},
{
  id:21,
  name: 'Gateway of India',
  description: 'Historic monument overlooking the Arabian Sea in Mumbai.',
  image: 'assets/Gateway-to-India.jpg',
  category: 'india',
  rating: 3,
  price: 8000,
  lat: 18.9220,
  lng: 72.8347
},
{
  id:22,
  name: 'Meenakshi Temple',
  description: 'Famous temple in Madurai known for its colorful towers.',
  image: 'assets/mennaksahi.jpg',
  category: 'india',
  rating: 5,
  price: 9000,
  lat: 9.9195,
  lng: 78.1193
},
{
  id:23,
  name: 'Jagannath Temple',
  description: 'Sacred temple in Puri known for the Rath Yatra festival.',
  image: 'assets/jagannath-temple.jpg',
  category: 'india',
  rating: 5,
  price: 11000,
  lat: 19.8135,
  lng: 85.8312
},
{
  id:24,
  name: 'Jaipur',
  description: 'Pink City famous for palaces and royal heritage.',
  image: 'assets/jaipur.jpg',
  category: 'india',
  rating: 3,
  price: 16000,
   lat: 26.9124,
  lng: 75.7873
},
{
  id:25,
  name: 'Gangtok',
  description: 'Capital of Sikkim with scenic Himalayan views.',
  image: 'assets/gangtok.jpg',
  category: 'india',
  rating: 4,
  price: 22000,
  lat: 27.3389,
  lng: 88.6065
},
{
  id:26,
  name: 'Red Fort',
  description: 'Historic Mughal fort in Delhi and UNESCO heritage site.',
  image: 'assets/redfort.jpg',
  category: 'india',
  rating: 4,
  price: 9000,
 lat: 28.6562,
  lng: 77.2410
},
{
  id:27,
  name: 'Golden Temple',
  description: 'Spiritual center of Sikhism located in Amritsar.',
  image: 'assets/golden temple.jpg',
  category: 'india',
  rating: 5,
  price: 12000,
  lat: 31.6200,
  lng: 74.8765
},
{
  id:28,
  name: 'Hong Kong',
  description: 'Vibrant city known for skyline, shopping and harbor views.',
  image: 'assets/Hong kong.jpg',
  category: 'international',
  rating: 4,
  price: 85000,
  lat: 22.3193,
  lng: 114.1694
},
{
  id:29,
  name: 'Tokyo',
  description: 'Modern city with rich culture and technology.',
  image: 'assets/tokyo.jpg',
  category: 'international',
  rating: 3,
  price: 90000,
  lat: 35.6762,
  lng: 139.6503
},
{
  id:30,
  name: 'Vietnam',
  description: 'Beautiful country known for landscapes and street food.',
  image: 'assets/vietnam.jpg',
  category: 'international',
  rating: 4,
  price: 70000,
  lat: 21.0278,
  lng: 105.8342
},
{
  id:31,
  name: 'Bangkok',
  description: 'Thailand capital famous for temples and nightlife.',
  image: 'assets/bangkok.jpg',
  category: 'international',
  rating: 4,
  price: 65000,
  lat: 13.7563,
  lng: 100.5018
},
{
  id:32,
  name: 'Bali',
  description: 'Indonesian island known for beaches and temples.',
  image: 'assets/bali.jpg',
  category: 'international',
  rating: 2,
  price: 75000,
 lat: -8.3405,
  lng: 115.0920
},
{
  id:33,
  name: 'Abu Dhabi',
  description: 'Luxury destination with grand mosques and desert safari.',
  image: 'assets/abu dhabi.jpg',
  category: 'international',
  rating: 4,
  price: 80000,
  lat: 24.4539,
  lng: 54.3773
},
{
  id:34,
  name: 'Nepal',
  description: 'Famous hill station in known for tea plantations and misty mountains.',
  image: 'assets/munnar.jpg',
  category: 'india',
  rating: 3,
  price: 15000,
  lat: 27.7172,
  lng: 85.3240
},
{
  id:35,
  name: 'Singapore',
  description: 'Modern city-state known for gardens and skyline.',
  image: 'assets/sing.jpg',
  category: 'international',
  rating: 5,
  price: 88000,
  lat: 1.3521,
  lng: 103.8198
},
{
  id:36,
  name: 'Munnar',
  description: 'Famous hill station in Kerala known for tea plantations and misty mountains.',
  image: 'assets/munnar1.jpg',
  category: 'india',
  rating: 4,
  price: 15000,
  lat: 10.0889,
lng: 77.0595
},
{
  id:37,
  name: 'Shillong',
  description: 'Beautiful hill station called the Scotland of the East.',
  image: 'assets/shillong.jpg',
  category: 'india',
  rating: 4,
  price: 18000,
  lat: 25.5788,
  lng: 91.8933
},
{
  id:38,
  name: 'Statue of Unity',
  description: 'World’s tallest statue dedicated to Sardar Vallabhbhai Patel.',
  image: 'assets/statue-of-unity.jpg',
  category: 'india',
  rating: 4,
  price: 12000,
  lat: 21.8380,
  lng: 73.7191
},
{
  id:39,
  name: 'Katra (Vaishno Devi)',
  description: 'Holy pilgrimage town and base for Vaishno Devi temple trek.',
  image: 'assets/katra.jpg',
  category: 'india',
  rating: 5,
  price: 10000,
  lat: 32.9916,
  lng: 74.9316
},
{
  id:40,
  name: 'Aurangabad',
  description: 'Historic city known for Ajanta and Ellora caves.',
  image: 'assets/aurangabad,jpg.jpg',
  category: 'india',
  rating: 4,
  price: 14000,
  lat: 19.8762,
  lng: 75.3433
},
{
  id:41,
  name: 'Rajas Seat Coorg',
  description: 'Famous sunset viewpoint surrounded by scenic valleys.',
  image: 'assets/rajas-seat.jpg',
  category: 'india',
  rating: 4,
  price: 16000,
  lat: 12.4210,
  lng: 75.7382
},
{
  id:42,
  name: 'Kolkata',
  description: 'Cultural capital of India known for heritage and festivals.',
  image: 'assets/kolkata.jpg',
  category: 'india',
  rating: 4,
  price: 13000,
  lat: 22.5726,
  lng: 88.3639
},
{
  id:43,
  name: 'Nubra Valley',
  description: 'Cold desert valley in Ladakh famous for sand dunes and monasteries.',
  image: 'assets/Nubra Valley.jpg',
  category: 'india',
  rating: 5,
  price: 25000,
  lat: 34.5944,
  lng: 77.5676
},
{
  id:44,
  name: 'Sahara desert',
  description: 'Desert valley in Ladakh famous for sand dunes and monasteries.',
  image: 'assets/Nubra Valley.jpg',
  category: 'india',
  rating: 5,
  price: 25000,
  lat: 25.4162,
  lng: 14.4387
},
{
  id:45,
  name: 'Dwaraka',
  description: 'Ancient holy city associated with Lord Krishna.',
  image: 'assets/dwaraka.jpg',
  category: 'india',
  rating: 4,
  price: 11000,
  lat: 22.2442,
  lng: 68.9685
},
{
  id:46,
  name: 'Rameshwaram',
  description: 'Sacred island town famous for Ramanathaswamy temple.',
  image: 'assets/rameshwaram.jpg',
  category: 'india',
  rating: 4,
  price: 12000,
  lat: 9.2881,
  lng: 79.3129
},

{
  id:47,
  name: 'Malaysia',
  description: 'Beautiful Southeast Asian country known for beaches and skyscrapers.',
  image: 'assets/malaysia.jpg',
  category: 'international',
  rating: 4,
  price: 65000,
  lat: 3.1390,
  lng: 101.6869
},
{
  id:48,
  name: 'London',
  description: 'Beautiful Southeast European country known for beaches and skyscrapers.',
  image: 'assets/london1.jpg',
  category: 'international',
  rating: 4,
  price: 65000,
  lat: 51.5074,
  lng: -0.1278
},
{
  id:49,
  name: 'Thailand',
  description: 'Popular travel destination with beaches, temples, and nightlife.',
  image: 'assets/thailand.jpg',
  category: 'international',
  rating: 4,
  price: 55000,
  lat: 13.7563,
  lng: 100.5018
},
{
  id:50,
  name: 'Austraila',
  description: 'Popular travel destination with beaches, places, and nightlife.',
  image: 'assets/thailand.jpg',
  category: 'international',
  rating: 4,
  price: 55000,
  lat: -33.8688,
  lng: 151.2093
},
{
  id:51,
  name: 'Indonesia',
  description: 'Island nation famous for Bali and tropical landscapes.',
  image: 'assets/indonesia.jpg',
  category: 'international',
  rating: 4,
  price: 60000,
  lat: -6.2088,
  lng: 106.8456
},
{
  id:52,
  name: 'Greece',
  description: 'Historic European country known for islands and ancient ruins.',
  image: 'assets/greece.jpg',
  category: 'international',
  rating: 4,
  price: 85000,
  lat: 37.9838,
  lng: 23.7275

},
{
  id:53,
  name: 'Canada',
  description: 'Beautiful country with mountains, lakes, and modern cities.',
  image: 'assets/canada.jpg',
  category: 'international',
  rating: 5,
  price: 95000,
  lat: 45.4215,
  lng: -75.6972
},
{
  id:54,
  name: 'Italy',
  description: 'Famous for art, architecture, and romantic cities.',
  image: 'assets/italy.jpg',
  category: 'international',
  rating: 5,
  price: 88000,
  lat: 45.4215,
  lng: -75.6972
},
{
  id:55,
  name: 'New Zealand',
  description: 'Adventure paradise with stunning mountains and lakes.',
  image: 'assets/new-zealand.jpg',
  category: 'international',
  rating: 5,
  price: 100000,
  lat: -41.2866,
  lng: 174.7756
},
{
  id:56,
  name: 'Egypt',
  description: 'Historic land of pyramids, deserts, and ancient civilization.',
  image: 'assets/egypt.jpg',
  category: 'international',
  rating: 4,
  price: 80000,
  lat: 30.0444,
  lng: 31.2357
},
{
  id:57,
  name: 'United Kingdom',
  description: 'Historic country known for London, castles, and culture.',
  image: 'assets/uk.jpg',
  category: 'international',
  rating: 4,
  price: 85000,
  lat: 51.5074,
  lng: -0.1278
}
]